In [41]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
device = 'mps'
print(device)

mps


# Loading data

## Initial Preparation

First define where the training data url is

In [42]:
import os 
cwd = os.getcwd()
repository_dir = '/'.join(cwd.split('/')[:-1])
# DATA_DIR = f'{repository_dir}/data/data/preprocessed/preprocessed.txt'
DATA_DIR = 'input.txt'
assert os.path.exists(DATA_DIR), 'Make sure you follow the steps of README.md in data repository'

print(f'Training data located at {DATA_DIR}')

Training data located at input.txt


Then load the data

In [43]:
with open(DATA_DIR, 'r', encoding='utf-8') as train_file:
    raw_data = train_file.read()


# Inspection
print(f'Loaded {len(raw_data)} characters')
print(f'First 100 characters:\n{raw_data[:100]}')

Loaded 1115394 characters
First 100 characters:
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


## Tokenization

Tokenization is essentially turning the data into 'words' that the model understands. Below the vocabulary that is defined is based on a character basis. 

TODO: check out other tokenizers:
tiktoken - https://github.com/openai/tiktoken
sentencepiece - https://github.com/google/sentencepiece

In [44]:
chars = sorted(list(set(raw_data)))
VOCAB_SIZE = len(chars)
print(f'Vocabulary ({VOCAB_SIZE} characters): {"".join(chars)}')
char_to_digit = {char:digit for digit, char in enumerate(chars)}
digit_to_char = {digit:char for digit, char in enumerate(chars)}

encode = lambda string: [char_to_digit[char] for char in string]
decode = lambda digits: ''.join([digit_to_char[digit] for digit in digits])

Vocabulary (65 characters): 
 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


In [45]:
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(raw_data), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

## Train/Val Split

In [46]:
TRAIN_PROPORTION = 0.9 # 90% of data is for training, 10% for validation
idx = int(TRAIN_PROPORTION * len(data)) 
train_data = data[:idx]
val_data = data[idx:]

## Chunking data

It is important to note that it is computationaly infeasible and prohibitive to train on the **whole** dataset all at once, due to the large training data size. This is why data is separated into *chunks*, which are smaller random samples of the whole dataset. The size of the chunks is defined by the variable `block_size`

### Blocks

In [47]:
BLOCK_SIZE = 64
train_data[:BLOCK_SIZE+1]


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50])

The way training is carried out is that for every character `c` in a chunk, `c` is the label and the inputs are all characters before `c`. 
This approach is useful, because the model can start predicting from as little as a single character, and predict everything up until block size
#### Example:

In [48]:
example = "Hello, there"
print(f"Input{' ' * 7}| Output")
print('='*22)
for t in range(1, len(example)):
    inputs = example[:t]
    output = example[t]

    print(f"{inputs:<11} | {output}")


Input       | Output
H           | e
He          | l
Hel         | l
Hell        | o
Hello       | ,
Hello,      |  
Hello,      | t
Hello, t    | h
Hello, th   | e
Hello, the  | r
Hello, ther | e


### Batch

There is an additional dimension except the time dimension (blocks), which is the batch. Multiple blocks are sampled and stacked on top of each other to create a batch. This way multiple samples can be processed in parallel.

In [49]:
BATCH_SIZE = 64
BLOCK_SIZE = 128
N_EMBD = 64
SEED = 1338

torch.manual_seed(SEED)

def get_batch(split = 'train'):
    data = train_data if split == 'train' else val_data
    # data = torch.tensor([i for i in range(100)])

    # Generate BATCH_SIZE random starting positions for each block
    block_indices = torch.randint(len(data) - BLOCK_SIZE, (BATCH_SIZE,)) 
    block_range = torch.arange(0, BLOCK_SIZE, dtype=torch.int)

    # Add the above range to each starting position to create a set
    # of indices for each block 
    block_ranges = block_indices[:, None] + block_range
    
    x = data[block_ranges] 
    y = data[block_ranges + 1]
    return x.to(device), y.to(device)    

print(get_batch())


(tensor([[43, 51, 40,  ..., 43,  1, 50],
        [20, 39, 58,  ..., 10,  0, 32],
        [ 1, 28, 46,  ..., 56,  7, 42],
        ...,
        [56, 10,  0,  ..., 58,  1, 31],
        [52, 53, 58,  ...,  0,  0, 35],
        [42,  1, 52,  ...,  1, 46, 53]], device='mps:0'), tensor([[51, 40, 56,  ...,  1, 50, 53],
        [39, 58, 46,  ...,  0, 32, 56],
        [28, 46, 53,  ...,  7, 42, 43],
        ...,
        [10,  0, 26,  ...,  1, 31, 43],
        [53, 58,  1,  ...,  0, 35, 13],
        [ 1, 52, 53,  ..., 46, 53, 59]], device='mps:0'))


## Loss Estimation

In [50]:
@torch.no_grad()
def estimate_loss(model, eval_iters = 10):
    out = {}
    model.eval()
    
    for split in ["test", "validation"]:
        losses = torch.zeros(eval_iters).to(device)
        for k in range(eval_iters):
            x, y = get_batch(split)
            loss = model(x, y)
            losses[k] = loss

        out[split] = losses.mean().item()

    model.train()
    return out

# Bigram Language Model

In [51]:
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def predict(self, input):
        return self.token_embedding_table(input)

    def forward(self, input, targets):

        # Number of channels is the same as the vocabulary size meaning for each letter
        # we have a vector of size VOCAB_SIZE storing the probability of each letter appearing
        logits = self.predict(input) # logits.shape = B, T, C - Batch, Time, Channels
        B, T, C = logits.shape
        transformed_logits = logits.view(B*T, C)
        targets = targets.view(B*T)
        loss = F.cross_entropy(transformed_logits, targets) # Expects B*T, C
        return loss
    
    def generate(self, input, max_characters=20):
        for _ in range(max_characters):
            logits = self.predict(input)
            logits = logits[:, -1, :]
            distribution = F.softmax(logits, dim=-1)
            next = torch.multinomial(distribution, num_samples=1)
            input = torch.cat((input, next), dim=1)
        return input[0]

# model = BigramLanguageModel(VOCAB_SIZE).to(device)
# x, y = get_batch()

# context = torch.zeros((1, 1), dtype=torch.long).to(device)
# res = model.generate(context)
# print(decode(res.tolist()))


## Training the model

In [52]:
import time

def train(model, epochs = 10000, learning_rate = 1e-3, eval_step = 1000):
    # https://arxiv.org/abs/1711.05101v3
    # https://paperswithcode.com/method/adamw
    optimizer = torch.optim.AdamW(model.parameters(), lr = learning_rate)
    start = time.time()

    for i in range(epochs):
        x, y = get_batch()
        loss = model(x, y)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        if i % eval_step == 0:
            print(f'Epoch {i} - {estimate_loss(model)}')
            end = time.time()
            print(f"Time taken: {end - start}")
            start = time.time()

# Self-attention 
Taking into consideration all previous characters.

Let's start by just taking the average of the previous characters.

In [54]:
import torch

B, T, C = 4, 8, 2

x = torch.randn(B, T, C)

print(x.shape)

torch.Size([4, 8, 2])


In [55]:
# Version 1

import torch

mask = torch.tril(torch.ones(T, T)) # returns the lower triangle of a matrix
mask /= mask.sum(axis=1, keepdim=True) # normalize the mask so each row sums to 1

print(mask @ x)

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])


In [56]:
# Version 2
# Using softmax to normalize the mask in order to directly be able to use the embedding table

import torch
import torch.nn.functional as F

mask = torch.tril(torch.ones(T, T)) # returns the lower triangle of a matrix
affinities = torch.ones(T, T)
affinities = affinities.masked_fill(mask == 0, float('-inf'))
affinities = F.softmax(affinities, dim=1)

print(affinities @ x)

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])


## Single Head to perform self-attention

In [57]:
import torch
import torch.nn as nn
import torch.nn.functional as F

B, T, C = 4, 8, 2
x = torch.randn(B, T, C)

# Head of self-attention
head_size = 16
keys = nn.Linear(C, head_size, bias=False)  # What is stored
query = nn.Linear(C, head_size, bias=False) # What is requied
value = nn.Linear(C, head_size, bias=False) 
k = keys(x)  # B, T, head_size
q = query(x) # B, T, head_size

v = value(x) # Multiply the affinities by this value instead of x



An intuitive way to think about the query is that for example for a vowel a consonant 2 positions earlier might be more important and this is reflected using the query. 
In other words it is a way to weight the positions in a data dependent manner. The keys layer on the other hand shows what is contained as weights. In the case of the previous example, if it is important that there is a consonant 2 letters before and there is infact a consonant the dot product will yield a high affinitie.

### Calculating the affinities

In [58]:
# Set the affinities to the dot product of the keys and queries instead of to a torch of ones
# The affinities are a weighted average where the weights are defined by the query and the 
# actual values are defined by the keys
affinities = k @ q.transpose(-1, -2) # (B, T, head_size) @ (B, head_size, T) = (B, T, T)

The problem with just mutliplying the keys by the queries will yield variance of the order of 
`head_size` when weights are initialized. Why?

(Attention is all you need https://arxiv.org/abs/1706.03762)

In [59]:
B, T, head_size = 4, 8, 15
sample_size = 100

k_var = 0
q_var = 0
affinities_var = 0

for _ in range(sample_size):
    k = torch.randn(B, T, head_size)
    q = torch.randn(B, T, head_size)
    affinities = k @ q.transpose(-1, -2)

    k_var += k.var()
    q_var += q.var()
    affinities_var += affinities.var()

print(k_var / sample_size)
print(q_var / sample_size)
print(affinities_var / sample_size)

tensor(0.9924)
tensor(0.9984)
tensor(14.7944)


This is because rand initializes the tensor with numbers drawn from a gaussian distribution (i.e. they have a 0-mean and a 1-variance). 
This means that the dot product of matrix where each row/column is a vector with 0-mean and 1-variance will result in the summing up of `head_size` number of vectors with 1-variance and the vectors in the resulting matrix will have `1 * head_size` variance. See proof below


In [60]:
sample_size = 100000
sum = 0
head_size = 3
for _ in range(sample_size):
    a = torch.randn(head_size, 3)
    b = torch.randn(head_size, 3)

    sum += (a @ b * head_size ** -0.5).var()

print(sum / sample_size)


# k = sqrt(head_size)
# sigma_a = E[a^2 / k^2] = E[a^2] / head_size
# 
# sigma_t = sigma_a + sigma_b = (E[a^2] + E[b^2]) / head_size


tensor(1.0011)


#### Motivation

The reason why it is important to normalize the weights (especially in the initial training) is that the softmax function converges to one-hot encoding of the largest value when there are very positive and very negative values in the same vector. See example below. This means that without the normalization information would be aggregated only from the highest-valued node which loses a lot of information.

In [61]:
a = torch.randn(5)
sharp_a = a * 10
print(F.softmax(a, dim=0)) # Values are fairly diffuse
print((F.softmax(sharp_a, dim=0, dtype=torch.float32) * 10000).round()/10000) # Approximates 1-hot encoding

tensor([0.2864, 0.1269, 0.1356, 0.3949, 0.0563])
tensor([0.0387, 0.0000, 0.0000, 0.9613, 0.0000])


In [62]:
mask = torch.tril(torch.ones(T, T)) 
affinities = affinities.masked_fill(mask == 0, float('-inf'))
affinities = F.softmax(affinities, dim=-1)

print(v.shape)
print(affinities.shape)
print((affinities @ v).shape)

torch.Size([4, 8, 16])
torch.Size([4, 8, 8])
torch.Size([4, 8, 16])


### Bringing everything together

In [63]:
class Head(nn.Module):

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(N_EMBD, head_size, bias=False)
        self.query = nn.Linear(N_EMBD, head_size, bias=False)
        self.value = nn.Linear(N_EMBD, head_size, bias=False)
        # Not a parameter of the module, so a pytorch naming convention
        self.register_buffer("mask", torch.tril(torch.ones(BLOCK_SIZE, BLOCK_SIZE)))

    def forward(self, inputs):
        B, T, C = inputs.shape
        k = self.key(inputs)
        q = self.query(inputs)
        v = self.value(inputs)
        
        affinities = k @ q.transpose(-1, -2) * (C ** -0.5)
        affinities = affinities.masked_fill(self.mask[:T, :T] == 0, float('-inf'))
        affinities = F.softmax(affinities, dim=1)

        return affinities @ v

In [64]:
class BigramLanguageModelSelfAttention(nn.Module):
   
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, N_EMBD)
        self.position_embedding_table = nn.Embedding(BLOCK_SIZE, N_EMBD)
        self.sa_head = Head(N_EMBD)
        self.lm_head = nn.Linear(N_EMBD, vocab_size)

    def predict(self, input):
        B, T = input.shape
        tok_embd = self.token_embedding_table(input)
        pos_embd = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_embd + pos_embd

        x = self.sa_head(x)
        x = self.lm_head(x)
        return x

    def forward(self, input, targets):
        logits = self.predict(input)
        B, T, C = logits.shape
        logits = logits.view(B*T, C)
        targets = targets.view(B*T)
        loss = F.cross_entropy(logits, targets)
        return loss

    def generate(self, input, max_characters=20):
        for _ in range(max_characters):
            # Crop the input to the last BLOCK_SIZE tokens
            input_cond = input[:, -BLOCK_SIZE:]

            logits = self.predict(input_cond)
            logits = logits[:, -1, :]
            distribution = F.softmax(logits, dim=-1)
            next = torch.multinomial(distribution, num_samples=1)
            input = torch.cat((input_cond, next), dim=1)
        return input_cond[0]

# Multi-Head attention

In [65]:
class MultiHeadAttention(nn.Module):

    def __init__(self, n_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(n_heads)])

    def forward(self, inputs):
        B, T, C = inputs.shape
        x = torch.cat([head(inputs) for head in self.heads], dim=-1)
        return x

In [66]:
class BigramLanguageModelMultiHeadAttention(nn.Module):
   
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, N_EMBD)
        self.position_embedding_table = nn.Embedding(BLOCK_SIZE, N_EMBD)
        # Create 4 heads with size N_EMBD / 4, works like group convolution, where each head corresponds to a part of an image
        self.sa_heads = MultiHeadAttention(4, N_EMBD // 4)

        self.lm_head = nn.Linear(N_EMBD, vocab_size)

    def predict(self, input):
        B, T = input.shape
        tok_embd = self.token_embedding_table(input)
        pos_embd = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_embd + pos_embd

        x = self.sa_heads(x)
        x = self.lm_head(x)
        return x

    def forward(self, input, targets):
        logits = self.predict(input)
        B, T, C = logits.shape
        logits = logits.view(B*T, C)
        targets = targets.view(B*T)
        loss = F.cross_entropy(logits, targets)
        return loss

    def generate(self, input, max_characters=20):
        for _ in range(max_characters):
            # Crop the input to the last BLOCK_SIZE tokens
            input_cond = input[:, -BLOCK_SIZE:]

            logits = self.predict(input_cond)
            logits = logits[:, -1, :]
            distribution = F.softmax(logits, dim=-1)
            next = torch.multinomial(distribution, num_samples=1)
            input = torch.cat((input_cond, next), dim=1)
        return input_cond[0]

# Feed-forward 

In [67]:
class FeedForward(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        # self.net = nn.Sequential(
        #     nn.Linear(n_features, 4 * n_features),
        #     nn.GELU(),
        #     nn.Linear(4 * n_features, n_features),
        # )
        self.net = nn.Sequential(
            nn.Linear(n_features, 4*n_features),
            nn.ReLU(),
            nn.Linear(4*n_features, n_features),
        )
    
    def forward(self, inputs):
        return self.net(inputs)

In [68]:
class BigramLanguageModelMultiHeadAttentionFeedForward(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, N_EMBD)
        self.position_embedding_table = nn.Embedding(BLOCK_SIZE, N_EMBD)

        self.sa_heads = MultiHeadAttention(4, N_EMBD // 4)
        self.ff = FeedForward(N_EMBD)
        self.lm = nn.Linear(N_EMBD, vocab_size)

    def predict(self, input):
        B, T = input.shape
        tok_embd = self.token_embedding_table(input)
        pos_embd = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_embd + pos_embd

        x = self.sa_heads(x)
        x = self.ff(x)
        x = self.lm(x)
        return x
    
    def forward(self, input, targets):
        logits = self.predict(input)
        B, T, C = logits.shape
        logits = logits.view(B*T, C)
        targets = targets.view(B*T)
        loss = F.cross_entropy(logits, targets)
        return loss
    
    def generate(self, input, max_characters):
        for _ in range(max_characters):
            # Crop the input to the last BLOCK_SIZE tokens
            input_cond = input[:, -BLOCK_SIZE:]

            logits = self.predict(input_cond)
            logits = logits[:, -1, :]
            distribution = F.softmax(logits, dim=-1)
            next = torch.multinomial(distribution, num_samples=1)
            input = torch.cat((input_cond, next), dim=1)
        return input_cond[0]

# Blocks
Blocks are a combination of an Attention Heads and a Feed Forward network. The idea is to chain multiple blocks to create a deep neural network.

In [69]:
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out
    
class MultiHeadAttentionProjection(nn.Module):

    def __init__(self, n_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(n_heads)])
        self.proj = nn.Linear(N_EMBD, N_EMBD)

    def forward(self, inputs):
        x = torch.cat([head(inputs) for head in self.heads], dim=-1)
        x = self.proj(x)
        return x

In [70]:
class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttentionProjection(n_head, head_size)
        self.ffwd = FeedForward(n_embd)
        # self.ln1 = nn.LayerNorm(n_embd)
        # self.ln2 = nn.LayerNorm(n_embd)

    # def forward(self, x):
    #     x = x + self.sa(self.ln1(x))
    #     x = x + self.ffwd(self.ln2(x))
    #     return x

    def forward(self, input):
        input = input + self.sa(input)
        input = input + self.ffwd(input)

        return input

In [71]:
class BigramLanguageModelBlocks(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, N_EMBD)
        self.position_embedding_table = nn.Embedding(BLOCK_SIZE, N_EMBD)

        self.blocks = nn.Sequential(*[Block(N_EMBD, 4) for _ in range(3)])
        self.lm = nn.Linear(N_EMBD, vocab_size)

    def predict(self, input):
        B, T = input.shape
        tok_embd = self.token_embedding_table(input)
        pos_embd = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_embd + pos_embd

        x = self.blocks(x)
        x = self.lm(x)
        return x
    
    def forward(self, input, targets):
        logits = self.predict(input)
        B, T, C = logits.shape
        logits = logits.view(B*T, C)
        targets = targets.view(B*T)
        loss = F.cross_entropy(logits, targets)
        return loss
    
    def generate(self, input, max_characters):
        for _ in range(max_characters):
            # Crop the input to the last BLOCK_SIZE tokens
            input_cond = input[:, -BLOCK_SIZE:]

            logits = self.predict(input_cond)
            logits = logits[:, -1, :]
            distribution = F.softmax(logits, dim=-1)
            next = torch.multinomial(distribution, num_samples=1)
            input = torch.cat((input_cond, next), dim=1)
        return input_cond[0]

# Testing out all models

In [72]:
# models = [BigramLanguageModelSelfAttention, BigramLanguageModelMultiHeadAttention, BigramLanguageModelMultiHeadAttentionFeedForward]
models = [BigramLanguageModelBlocks]
context = torch.zeros((1, 1), dtype=torch.long).to(device)
for model_cls in models:
    model = model_cls(VOCAB_SIZE).to(device)
    train(model, epochs=1000, eval_step=100)

Epoch 0 - {'test': 4.344202041625977, 'validation': 4.348072052001953}
Time taken: 0.4931068420410156
Epoch 100 - {'test': 2.56074595451355, 'validation': 2.565858840942383}
Time taken: 6.84815526008606
Epoch 200 - {'test': 1.9489948749542236, 'validation': 1.939949870109558}
Time taken: 6.9171671867370605
Epoch 300 - {'test': 1.0976828336715698, 'validation': 1.0865048170089722}
Time taken: 6.87441611289978
Epoch 400 - {'test': 0.6886070370674133, 'validation': 0.7017566561698914}
Time taken: 6.873816967010498
Epoch 500 - {'test': 0.5095464587211609, 'validation': 0.4988815486431122}
Time taken: 7.0769829750061035
Epoch 600 - {'test': 0.3704169988632202, 'validation': 0.3757950961589813}
Time taken: 7.040357351303101
Epoch 700 - {'test': 1.1924456357955933, 'validation': 1.18844735622406}
Time taken: 6.9651198387146
Epoch 800 - {'test': 0.5834463238716125, 'validation': 0.5986505150794983}
Time taken: 6.933932065963745
Epoch 900 - {'test': 0.38834553956985474, 'validation': 0.39535993

In [77]:
res = model.generate(context, max_characters=200)
print(decode(res.tolist()))

s
g btt g fbttttttttttt bbbatotbdd
Utofigttttttttttb
geeraupeeAy.
ONnsusured indereerwhsomery suesuidreh hftO this'sinhrg I'Thd 
